import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  content: {
    gap: 16,
    padding: 18,
    paddingBottom: 28,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  kicker: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 8,
  },
  title: {
    color: '#0f172a',
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 36,
  },
  subtitle: {
    color: '#64748b',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: '#0f172a',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  panel: {
    backgroundColor: '#ffffff',
    borderColor: '#e2e8f0',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  panelHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '900',
  },
  helpText: {
    color: '#64748b',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 5,
  },
  authMessage: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 18,
  },
  inputWrap: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderColor: '#cbd5e1',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 14,
  },
  input: {
    color: '#0f172a',
    flex: 1,
    fontSize: 16,
    minWidth: 0,
  },
  tabBar: {
    backgroundColor: '#e2e8f0',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 8,
  },
  tabButtonActive: {
    backgroundColor: '#0f766e',
  },
  tabText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '900',
  },
  tabTextActive: {
    color: '#ffffff',
  },
  stack: {
    gap: 14,
  },
  liveHero: {
    backgroundColor: '#111827',
    borderRadius: 8,
    gap: 18,
    padding: 18,
  },
  liveHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  liveLabel: {
    color: '#5eead4',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 5,
  },
  liveTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '900',
  },
  badge: {
    backgroundColor: '#f59e0b',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  badgeText: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '900',
  },
  scoreRow: {
    gap: 8,
  },
  score: {
    color: '#ffffff',
    fontSize: 46,
    fontWeight: '900',
    lineHeight: 52,
  },
  scoreMeta: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 20,
  },
  listPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#e2e8f0',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  matchRow: {
    alignItems: 'center',
    borderTopColor: '#e2e8f0',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 68,
    paddingTop: 12,
  },
  matchText: {
    flex: 1,
    minWidth: 0,
  },
  matchTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '900',
  },
  matchMeta: {
    color: '#64748b',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  statusPill: {
    backgroundColor: '#dcfce7',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusText: {
    color: '#166534',
    fontSize: 11,
    fontWeight: '900',
  },
  playersGrid: {
    gap: 10,
  },
  playerChip: {
    backgroundColor: '#f8fafc',
    borderColor: '#e2e8f0',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  playerLabel: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '800',
  },
  playerValue: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 4,
  },
  ballGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  ballButton: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderColor: '#cbd5e1',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 68,
    paddingVertical: 10,
    width: '22.6%',
  },
  ballLabel: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '900',
  },
  ballValue: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 3,
    textAlign: 'center',
  },
  scorerActions: {
    gap: 10,
  },
  adminStats: {
    flexDirection: 'row',
    gap: 10,
  },
  statTile: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#e2e8f0',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 98,
    padding: 12,
  },
  statValue: {
    color: '#0f172a',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 8,
  },
  statLabel: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  setupRow: {
    alignItems: 'center',
    borderTopColor: '#e2e8f0',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 62,
    paddingTop: 12,
  },
  setupIcon: {
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  apiText: {
    color: '#64748b',
    fontSize: 11,
    textAlign: 'center',
  },
});
